version: "3.9"

services:
  fastapi_be:
    build: ./fastapi_be
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_be:/app
    restart: always
    depends_on:
      - react-fe
      - postgres

  react-fe:
    build: ./react-fe
    ports:
      - "3000:3000"
    volumes:
      - ./react-fe:/app
      - /app/node_modules
    restart: always

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always

volumes:
  postgres-data: