// Generated by chatGPT

export const INDUSTRY_TAG_COLOR = {
    "Agriculture": "#F44336",
    "Sports": "#E91E63",
    "Real Estate": "#9C27B0",
    "Manufacturing": "#673AB7",
    "Tourism and Hospitality": "#3F51B5",
    "Consumer Goods": "#2196F3",
    "Healthcare": "#03A9F4",
    "Services": "#00BCD4",
    "Fashion and Beauty": "#009688",
    "Energy": "#4CAF50",
    "Entertainment and Media": "#8BC34A",
    "Finance": "#CDDC39",
    "Retail": "#FFC107",
    "E-commerce": "#FF9800",
    "Infrastructure": "#FF5722",
    "Transportation": "#795548",
    "Space": "#9E9E9E",
    "Logistics and Supply Chain": "#607D8B",
    "Technology": "#E53935",
    "Telecommunications": "#D81B60",
    "Environment": "#8E24AA",
    "Education": "#5E35B1"
}
